Model api integration
SeCrey36/anynote_web pull request #2
Opened 2024-07-29 14:09 UTC by IWorkForFood

2024-07-29 14:47 UTC, egorgur requested changes
Make changes as we discussed.

2024-07-29 14:47 UTC, egorgur commented on anynote/main/migrations/0001_initial.py
> +    ]
You should not include migrations files in commits

2024-07-29 14:47 UTC, egorgur commented on anynote/api/views.py
> +            raise Http404("Note not found.")
As we discussed, rename this UserApiView to AccountApiView and return old UserApiView from older commit. The endpoint users/<int:pk> will be used for testing purposes.

2024-07-29 14:47 UTC, egorgur commented on anynote/api/views.py
>      """
Edit this DockString. It must represent actual view functionality.

2024-07-29 14:47 UTC, egorgur commented on anynote/api/urls.py
>      path("token/refresh/", tokenRefreshView, name="token_refresh"),
Why you have deleted path("users/<int:pk>/") to individual users? It is used to debug user info.
Undo its deletion

2024-07-29 14:47 UTC, egorgur commented on anynote/main/migrations/0001_initial.py
Do not include migrations files in branches and commits

2024-07-29 14:57 UTC, egorgur approved these changes
Great job, Michael! **<3**

2024-07-29 14:57 UTC, egorgur commented on anynote/api/urls.py
> +    path("user/<int:pk>", userApiView, name="userApi"),
Mistake in url naming. It should be user**s**/<int:pk>

2024-07-29 15:00 UTC, merged

2024-08-31 09:12 UTC, mrFroxyk commented on anynote/api/serializers.py
> +    hash = serializers.CharField(max_length=200, default="")
```suggestion
fdsfdsfsd
```